# File: .github/workflows/setup-node/action.yml
name: setup-node
description: "Setup Node.js ⚙️ - Cache dependencies ⚡ - Install dependencies 🔧"
inputs:
  path:
    description: "The subdirectory containing the Node.js project (e.g., frontend or backend)"
    required: true
    default: "frontend"

runs:
  using: "composite"
  steps:
    - name: Setup Node.js ⚙️
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'yarn'

    - name: Cache dependencies ⚡
      id: cache_dependencies
      uses: actions/cache@v3
      with:
        path: ${{ inputs.path }}/node_modules
        key: node-modules-${{ hashFiles('${{ inputs.path }}/package-lock.json') }}

    - name: Install dependencies 🔧
      shell: bash
      if: steps.cache_dependencies.outputs.cache-hit != 'true'
      run: |
        cd ${{ inputs.path }}
        npm ci